simple-cms/config/routes.rb
Rails.application.routes.draw do
  # Demo
  root 'demo#index'

  get 'about' => 'demo#about'
  get 'contact-us' => 'demo#contact_us'

  # Resources do not have the extra delete that was added in previous lessons.  In most cases
  # this would be done with Javascript for confirmation.  This would only be required if there
  # were say other changes that were going to happen due to the deletion.  For example:
  # - Applying children to another parent 
  # - Confirming that subdata (foreign key data) could be lost forever
  # - etc.
  # resources :subjects do 
  #   member do 
  #     get :delete
  #   end
  # end

  # Access Routes
  # Important part here is the `resource` fakeout to get the access_path created (I think)
  get 'menu' =>'access#menu'
  get 'login' => 'access#new'
  post 'access/new' => 'access#create'
  delete 'logout' => 'access#destroy'
 
  # Subject and Page Routes
  resources :subjects do 
    resources :pages
  end
  

  # Default route
  get ':controller(/:action(/:id))'
end

simple-cms/app/controllers/access_controller.rb
class AccessController < ApplicationController
  before_action :confirm_logged_in, except: [:new, :create]

  def menu
    @user_id = session[:user_id]
  end

  def new
  end

  def create
    logger.info("#{self.class} >> Processing login attempt with user: #{params[:username]}")    
    session[:user_id] = 1234
    cookies[:username] = params[:username]
    cookies[:language] = 'en'

    logger.info("#{self.class} >> Successfully logged in user: #{params[:username]}")

    redirect_to(menu_path)
  end

  def destroy
    logger.info("#{self.class} >> Logging user #{session[:user_id]} out")

    session[:user_id] = nil
    cookies.delete :username

    redirect_to(login_path)
  end
end

simple-cms/app/helpers/access_helper.rb
module AccessHelper
end

simple-cms/app/views/access/menu.html.erb
<h2>Welcome back, <%= "#{@username} (#{@user_id})" %></h2>
<ul>
    <li><%= link_to('Manage Subjects', subjects_path) %></li>
    <li><%= link_to('Logout', logout_path, method: :delete) %></li>
</ul>

simple-cms/app/views/access/new.html.erb
<h2>Login</h2>
<div class="container">
    <p>Simulate a login form</p>
</div>
<%= form_tag(access_new_path) do %>
<div class="container">
    <table summary="Login form">
        <tr>
            <th><%= label_tag(:username) %></th>
            <td><%= text_field_tag(:username, params[:username]) %></td>
        </tr>
        <tr>
            <th><%= label_tag(:password) %></th>
            <td><%= password_field_tag(:password, params[:password]) %></td>
        </tr>
    </table>
</div>
<div class="container form-buttons">
    <%= submit_tag("Login") %>
</div>
<% end %>