simple-cms/config/routes.rb
Rails.application.routes.draw do
  # Demo
  root 'demo#index'

  get 'about' => 'demo#about'
  get 'contact-us' => 'demo#contact_us'

  # Resources do not have the extra delete that was added in previous lessons.  In most cases
  # this would be done with Javascript for confirmation.  This would only be required if there
  # were say other changes that were going to happen due to the deletion.  For example:
  # - Applying children to another parent 
  # - Confirming that subdata (foreign key data) could be lost forever
  # - etc.
  # resources :subjects do 
  #   member do 
  #     get :delete
  #   end
  # end

  # Access Routes
  # Important part here is the `resource` fakeout to get the access_path created (I think)
  get 'menu' =>'access#menu'
  get 'login' => 'access#new'
  post 'access/new' => 'access#create'
  delete 'logout' => 'access#destroy'
 
  # Subject and Page Routes
  resources :subjects do 
    resources :pages
  end
  

  # Default route
  get ':controller(/:action(/:id))'
end

simple-cms/app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Page input table">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Permalink</th>
    <td><%= f.text_field(:permalink) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.number_field(:position) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Content</th>
    <td><%= f.text_area(:content) %></td>
  </tr>  
</table>

simple-cms/app/views/pages/edit.html.erb
<% content_for(:head_title) { "Edit Page #{@page.name}" }%>

<p>
<%= link_to("<< Back to #{@subject.name}", subject_path(@subject)) %>
</p>

<h2>Edit Page</h2>

<%= form_for(@page, :url => subject_page_path(@subject), :method => 'patch') do |f| %>

<%= render(partial: 'form', locals: { f: f }) %>

<div class="form-buttons">
  <%= f.submit("Save")%>
</div>
<% end %>

simple-cms/app/views/pages/new.html.erb
<% content_for(:head_title) { "Add new Page" }%>

<p>
<%= link_to("<< Back to #{@subject.name}", subject_path(@subject)) %>
</p>

<h2>Add Pages</h2>

<%= form_for(@page, :url => subject_pages_path(@subject), :method => 'post') do |f| %>

<%= render(partial: 'form', locals: { f: f }) %>

<div class="form-buttons">
  <%= f.submit("Create")%>
</div>
<% end %>