simple-cms/config/routes.rb
Rails.application.routes.draw do
  # Demo
  root 'demo#index'

  get 'about' => 'demo#about'
  get 'contact-us' => 'demo#contact_us'

  # Resources do not have the extra delete that was added in previous lessons.  In most cases
  # this would be done with Javascript for confirmation.  This would only be required if there
  # were say other changes that were going to happen due to the deletion.  For example:
  # - Applying children to another parent 
  # - Confirming that subdata (foreign key data) could be lost forever
  # - etc.
  # resources :subjects do 
  #   member do 
  #     get :delete
  #   end
  # end

  # Access Routes
  # Important part here is the `resource` fakeout to get the access_path created (I think)
  get 'menu' =>'access#menu'
  get 'login' => 'access#new'
  post 'access/new' => 'access#create'
  delete 'logout' => 'access#destroy'
 
  # Subject and Page Routes
  resources :subjects do 
    resources :pages
  end
  

  # Default route
  get ':controller(/:action(/:id))'
end

simple-cms/app/models/subject.rb
class Subject < ApplicationRecord

  # Subjects have Pages that will be removed on destroy
  has_many :pages, dependent: :destroy

  scope :visible, lambda { where(visible: true) }
  scope :invisible, lambda { where(visible: false) }
  scope :sorted, lambda { order(:position) }
  scope :search_name, lambda { |lookup| where("UPPER(name) like ?", "%#{lookup.upcase}%")}
  # scope :search_name, -> (lookup) { |lookup| where("UPPER(name) like ?", "%#{lookup.upcase}%")}

  validates :name, presence: true, length: { maximum: 50}
  validates :position, presence: true, numericality: { greater_than: 0 }
  validates :visible, inclusion: [true, false]

  after_save :log_save, if: Proc.new { |s| s.pages.visible.any? }

  before_validation :titleize_name

private

  def log_save 
    logger.info "Saved subject #{id} #{name}; subject has visible pages."
  end 

  def titleize_name
    self.name = name.titleize
  end 
end

simple-cms/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :confirm_logged_in

  # index.html
  def index
    @subjects = Subject.order('position ASC')
  end

  # show.html
  def show
    @subject = Subject.find(params[:id])
  end

  # new.html
  def new
    @subject = Subject.new
  end

  def create    
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:success] = "Subject #{@subject.name} was created successfully"
      redirect_to subjects_path
    else 
      render :new
    end 
  end 

  # edit.html
  def edit
    @subject = Subject.find(params[:id])
  end

  def update 
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      flash[:success] = "Subject #{@subject.name} was updated successfully"
      redirect_to subjects_path
    else 
      render :edit
    end 
  end

  def destroy
    @subject = Subject.find(params[:id])
    if @subject.destroy 
      flash[:success] = "Subject #{@subject.name} was deleted successfully"
      redirect_to subjects_path 
    else 
      flash[:error] = "Could not delete subject #{@subject.name}"
      redirect_to subjects_path 
    end 
  end

private 

  def subject_params
    params.require(:subject).permit(:name, :position, :visible)
  end 

end

simple-cms/app/helpers/subjects_helper.rb
module SubjectsHelper

end

simple-cms/app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Subject input table">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.number_field(:position) %></td>
  </tr>
  <tr>
    <th><%= f.label(:visible)%></th>
    <td>Visible: <%= f.radio_button(:visible, true) %> Hidden: <%= f.radio_button(:visible, false) %></td>
  </tr>
</table>

simple-cms/app/views/subjects/edit.html.erb
<% content_for(:head_title) { "Edit Subject #{@subject.name}" }%>

<p>
<%= link_to('<< Back to Subjects', subjects_path) %>
</p>

<h2>Edit Subject</h2>

<%= form_for(@subject, :url => subject_path, :method => 'patch') do |f| %>

<%= render(partial: 'form', locals: { f: f }) %>

<div class="form-buttons">
  <%= f.submit("Save")%>
</div>
<% end %>

simple-cms/app/views/subjects/index.html.erb
<% content_for(:head_title) { "Subjects List" }%>

<div class="">
  <div id="subjects-navbar" class="flex flex-row justify-between content-center">
    <p class="text-2xl">All Subjects</p>
    <%= link_to("Add Subject", new_subject_path, :class => 'action new', :role=> 'button')%>      
  </div>
</div>

<div class="">
  <table class="table-auto" summary="Subjects List">
    <tr class="header">
      <th class="w-2">#</th>
      <th>Subject</th>
      <th class="w-2">Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
  <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= status_tag(subject.visible, { true_text: 'Yes', false_text: 'No' }) %></td>
      <td class="center"><%= subject.pages.size %> <%= pluralize(subject.pages.size, 'Page') %></td>
      <td class="center">
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", subject_path(subject), method: :delete, :class => 'action delete') %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

simple-cms/app/views/subjects/new.html.erb
<% content_for(:head_title) { "Add New Subject" }%>

<p>
<%= link_to('<< Back to Subjects', subjects_path) %>
</p>

<h2>Add Subject</h2>

<%= form_for(@subject, :url => subjects_path, :method => 'post') do |f| %>

<%= render(partial: 'form', locals: { f: f }) %>

<div class="form-buttons">
  <%= f.submit("Create")%>
</div>
<% end %>

simple-cms/app/views/subjects/show.html.erb
<% content_for(:head_title) { "Subject #{@subject.name}" }%>
<% content_for(:footer) do %> 
  <p>You can add or edit the subjects on this screen.</p>
<% end %>

<p>
<%= link_to('<< Back to Subjects', subjects_path) %>
</p>

<h2><%= @subject.name %> (<%= @subject.position%>)</h2>

<table summary="Display subject details">
  <tr>
    <th>Visible?</th>
    <td><%= @subject.visible ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
    <th>Created</th>
    <td><%= @subject.created_at.strftime("%d %b, %Y") %></td>
  </tr>   
  <tr>
    <th>Updated</th>
    <td><%= @subject.updated_at.strftime("%d %b, %Y") %></td>
  </tr>  
</table>
<p>
<%= link_to("Edit", edit_subject_path(@subject), class: 'action edit', 'data-role': 'button') %>
</p>

<h2>Pages</h2>
<table summary="Display subject pages">
  <tr>
    <th>#</th>
    <th>Page Name</th>    
    <th>Permalink</th>
    <th>Visible</th>
    <th>Actions</th>
  </tr>
  <% @subject.pages.each do |page| %>
  <tr>
    <td><%= page.position %></td>
    <td><%= page.name %></td>
    <td><%= page.permalink %></td>
    <td><%= page.visible ? 'Yes' : 'No' %></td>
    <td class="center">
      <%= link_to("Edit", edit_subject_page_path(page.subject, page), :class => 'action edit') %>
      <%= link_to("Delete", subject_page_path(page.subject, page), method: :delete, :class => 'action delete') %>
    </td>
  </tr>
  <% end %>
</table>
<p>
<%= link_to("Add Page", new_subject_page_path(@subject)) %>
</p>